# Generated by Django 4.1.5 on 2023-02-04 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contactform_person_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BlogTitle', models.CharField(max_length=500)),
                ('BlogShortDescription', models.TextField()),
                ('BlogThumbnail', models.CharField(max_length=50)),
            ],
        ),
    ]
